name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fwilhe2/buildroot-action@main
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: buildroot-2024.02/output
